# Generated by Django 4.1.2 on 2023-01-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150, null=True)),
                ('house', models.CharField(max_length=200)),
                ('land_mark', models.CharField(max_length=200)),
                ('street_address', models.CharField(max_length=200, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('phone', models.IntegerField(blank=True, unique=True)),
                ('order_id', models.TextField(max_length=200)),
            ],
        ),
    ]
