# Generated by Django 4.1.2 on 2023-01-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Store',
            fields=[
                ('store_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('land_mark', models.CharField(max_length=200)),
                ('building_no', models.IntegerField()),
                ('license_no', models.CharField(max_length=200)),
                ('owner_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=100)),
                ('pincode', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
    ]
