# Generated by Django 4.1.2 on 2023-01-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('pd_id', models.AutoField(primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='products')),
                ('price', models.IntegerField()),
                ('product_id', models.IntegerField(unique=True)),
                ('category', models.CharField(max_length=200)),
                ('store_id', models.IntegerField()),
                ('quantity', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True, max_length=200)),
            ],
        ),
    ]
